In [336]:
#Tasks:  
#1 Calculate annual elasticities for Price v. Enrollment 
#2 Calculate Tuition v. credit hour 

In [337]:
#Import Relevant Libraries 
import numpy as np
import pandas as pd
#Ignore warnings since division by 0 is sometimes expected in Elasticity calculations
import warnings
warnings.filterwarnings('ignore',message="divide by zero encountered in divide")

# Create Data Vectors

In [338]:
#Create a Vector for year
Year = []
yrange = range(2000,2021) #Remember, Python indexes from 0 so upper limit is n2 + 1 
for y in yrange:
    Year.append(y)

In [339]:
#Check Year Vector 
print(Year)
len(Year) #count elements 

[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]


21

In [340]:
#Create a Vector for Enrollment
Enrollment = [3422,	3419,	3543,	3655,	3910,	3940,	3594,	3556,	3903,	4220,	4058,	4134,	4124,	3674,	3202,	2775,	2587,	2637,	2511,	2577,	2553,
]

In [341]:
#Check Enrollment Vector 
print(Enrollment)
len(Enrollment) #count elements

[3422, 3419, 3543, 3655, 3910, 3940, 3594, 3556, 3903, 4220, 4058, 4134, 4124, 3674, 3202, 2775, 2587, 2637, 2511, 2577, 2553]


21

In [342]:
#Create a Vector for Credits 
Credits = [90624,	94446,	96039,	101352,	101868,	100181,	92486,	92123,	94639,	101972,	98137,	98372,	93163,	85292,	87907,	91021,	94077,	115340,	137467,	165057,	191712,
]

In [343]:
#Check Credits Vector
print(Credits)
len(Credits) #count elements 

[90624, 94446, 96039, 101352, 101868, 100181, 92486, 92123, 94639, 101972, 98137, 98372, 93163, 85292, 87907, 91021, 94077, 115340, 137467, 165057, 191712]


21

In [344]:
#Create a Price (Tuition and Fees) Vector 
Price = [1025,	1150,	1184,	1442,	1545,	1621,	1667,	1667,	1751,	1867,	2062,	2247,	2472,	2803,	3084,	3355,	3417,	3417,	3663,	3663,	3663,
]

In [345]:
#Check Price Vector
print(Price)
len(Price)

[1025, 1150, 1184, 1442, 1545, 1621, 1667, 1667, 1751, 1867, 2062, 2247, 2472, 2803, 3084, 3355, 3417, 3417, 3663, 3663, 3663]


21

# Merge Vectors into a Data Frame

In [346]:
#Create an Array from the Vectors 
data = np.hstack((Year,Price,Enrollment,Credits)).reshape(21,4,order ="F")
print(data)

[[  2000   1025   3422  90624]
 [  2001   1150   3419  94446]
 [  2002   1184   3543  96039]
 [  2003   1442   3655 101352]
 [  2004   1545   3910 101868]
 [  2005   1621   3940 100181]
 [  2006   1667   3594  92486]
 [  2007   1667   3556  92123]
 [  2008   1751   3903  94639]
 [  2009   1867   4220 101972]
 [  2010   2062   4058  98137]
 [  2011   2247   4134  98372]
 [  2012   2472   4124  93163]
 [  2013   2803   3674  85292]
 [  2014   3084   3202  87907]
 [  2015   3355   2775  91021]
 [  2016   3417   2587  94077]
 [  2017   3417   2637 115340]
 [  2018   3663   2511 137467]
 [  2019   3663   2577 165057]
 [  2020   3663   2553 191712]]


In [347]:
LSUSdata = pd.DataFrame(data, columns = ["Year","Price","Enrollment","Credits"])
LSUSdata.head()

Year  Price  Enrollment  Credits
0  2000   1025        3422    90624
1  2001   1150        3419    94446
2  2002   1184        3543    96039
3  2003   1442        3655   101352
4  2004   1545        3910   101868

# Elasticity Calculation Function

In [329]:
#Formulas
#Elasticity = %change in Q/%change in P 
#%change = (x2-x1)/x1

In [348]:
#Check how to call elements by row label and column name
LSUSdata.loc[2,"Year"]

2002

In [363]:
#Function to calculate elasticites and insert them into the data frame 
df = LSUSdata
irange = range(1,21)
Elasticity1 = []
Elasticity2 = []
def elasticityfunc(Q1,Q2,P,elasticity1name,elasticity2name,dfrename):
    for i in irange:
        Q1percentchange = ((df.loc[i,Q1] - df.loc[i-1,Q1])/df.loc[i-1,Q1])
        Q2percentchange = ((df.loc[i,Q2] - df.loc[i-1,Q2])/df.loc[i-1,Q2])
        Ppercentchange = ((df.loc[i,P] - df.loc[i-1,P])/df.loc[i-1,P])
        E1 = Q1percentchange/Ppercentchange 
        E2 = Q2percentchange/Ppercentchange
        Elasticity1.append(E1)
        Elasticity2.append(E2)
    Elasticity1.insert(0,"NULL")
    Elasticity2.insert(0,"NULL")
    df[elasticity1name] = np.array(Elasticity1)
    df[elasticity2name]=  np.array(Elasticity2)
    dfrename = df
    print(df)

In [364]:
#Test the Function   
elasticityfunc("Enrollment","Credits","Price","Enrollment_Elasticity","Credits_Elasticity","LSUSelasticity")

    Year  Price  Enrollment  Credits  Enrollment_Elasticity  \
0   2000   1025        3422    90624                   NULL   
1   2001   1150        3419    94446  -0.007188778492109878   
2   2002   1184        3543    96039     1.2267088760043356   
3   2003   1442        3655   101352    0.14507041945357918   
4   2004   1545        3910   101868     0.9767441860465117   
5   2005   1621        3940   100181    0.15597657827433034   
6   2006   1667        3594    92486     -3.094603840211874   
7   2007   1667        3556    92123                   -inf   
8   2008   1751        3903    94639      1.936529139214741   
9   2009   1867        4220   101972     1.2259954765123202   
10  2010   2062        4058    98137   -0.36754648195406486   
11  2011   2247        4134    98372     0.2087461537436895   
12  2012   2472        4124    93163  -0.024157393968714726   
13  2013   2803        3674    85292    -0.8149187865006549   
14  2014   3084        3202    87907    -1.281502992074

In [365]:
#Check to see if function has added new values to the data frame under its new name
LSUSelasticity

Year  Price  Enrollment  Credits  Enrollment_Elasticity  \
0   2000   1025        3422    90624                   NULL   
1   2001   1150        3419    94446  -0.007188778492109878   
2   2002   1184        3543    96039     1.2267088760043356   
3   2003   1442        3655   101352    0.14507041945357918   
4   2004   1545        3910   101868     0.9767441860465117   
5   2005   1621        3940   100181    0.15597657827433034   
6   2006   1667        3594    92486     -3.094603840211874   
7   2007   1667        3556    92123                   -inf   
8   2008   1751        3903    94639      1.936529139214741   
9   2009   1867        4220   101972     1.2259954765123202   
10  2010   2062        4058    98137   -0.36754648195406486   
11  2011   2247        4134    98372     0.2087461537436895   
12  2012   2472        4124    93163  -0.024157393968714726   
13  2013   2803        3674    85292    -0.8149187865006549   
14  2014   3084        3202    87907    -1.2815029920747312   
15  2015   3355        2775    91021    -1.5175801102170923   
16  2016   3417        2587    94077    -3.6660273176402205   
17  2017   3417        2637   115340                    inf   
18  2018   3663        2511   137467    -0.6636976608673937   
19  2019   3663        2577   165057                    inf   
20  2020   3663        2553   191712                   -inf   

      Credits_Elasticity  
0                   NULL  
1    0.34582891949152544  
2     0.5704940638347963  
3    0.25387748242780245  
4    0.07127634383139948  
5   -0.33666052352580117  
6     -2.706751866078919  
7                   -inf  
8     0.5419994903294405  
9     1.1696063006757802  
10  -0.36007596856653457  
11  0.026690211615367266  
12   -0.5288145678309547  
13   -0.6309673981083669  
14   0.30583006203683294  
15   0.40312546003729116  
16    1.8168228459153875  
17                   inf  
18    2.6647253930056207  
19                   inf  
20                   inf